### ISSUE TITLE
end event no fire in readableStreambuffer

### ISSUE THREAD

**Issue by Maxim-Chugaev** [samcday/node-stream-buffer#15]
```javascript
pngStream = new ReadableStreamBuffer
    pngStream.put buffer
    pngStream.on 'data', (chunk)->
      console.log chunk

    pngStream.on 'end', ()->
      console.log 'end'

    pngStream.on 'close', ->
      console.log 'close'
```
event end and close handler not called

**Comment by samcday** [comment]
@Maxim-Chugaev yep - the `ReadableStreamBuffer` will stay open until you call `destroySoon()` on it. This is documented in the [README](https://github.com/samcday/node-stream-buffer#readable-streambuffer) :)
