### ISSUE TITLE
Can we get a new release please?

### ISSUE THREAD

**Issue by bls** [samcday/node-stream-buffer#19]
Hi, I'm using stream-buffers 2.1.0 and I want the "finish" event from WritableStream to fire. I see that is there in github, but not available in NPM. Would it be possible to bump the version and publish a new version with that feature please?

**Comment by samcday** [comment]
`stream-buffers`@`2.2.0` released :)

**Comment by bls** [comment]
Wow that was fast, thanks :)  :+1:
