### ISSUE TITLE
end event not fired when .end() is called

### ISSUE THREAD

**Issue by pornel** [samcday/node-stream-buffer#24]
```js
var myWritableStreamBuffer = new streamBuffers.WritableStreamBuffer();
myWritableStreamBuffer.on('end', function(){
    console.log("should be called");
});
myWritableStreamBuffer.write('test');
myWritableStreamBuffer.end();
```

I expect "should be called" to be printed in this case, but it seems that the 'end' event is never fired.

### Another test case:

```js
var streamBuffers = require('stream-buffers');
var myWritableStreamBuffer = new streamBuffers.WritableStreamBuffer();

process.stdin.pipe(myWritableStreamBuffer).on('end', function(){
    console.log("buffering ended");
});
```

and run:

```sh
node test.js < /dev/null
```

Expected result: "buffering ended" printed. Actual result: nothing.

**Comment by samcday** [comment]
Hey @pornel - which version of the library are you using?

**Comment by pornel** [comment]
3.0.0. Node v5.2.0 on OS X 10.11.

**Comment by samcday** [comment]
Hey @pornel sorry for the delay in getting back to you (moving house!). In 3.0.0 `WritableStreamBuffer`  implements [`stream.Writable`](https://nodejs.org/api/stream.html#stream_class_stream_writable), so it emits `finish` when `end()` has been called and data has finished flushing out.

**Comment by pornel** [comment]
Oh, I see I've mixed up the events. Thanks for responding!
