### ISSUE TITLE
myReadableStreamBuffer.put with hex-data not working

### ISSUE THREAD

**Issue by jobe451** [samcday/node-stream-buffer#25]
Based on this example from the docu, I assumed that the put method can also be used with 'hex' as an attribute. However, it seems not to be the case.

Quote from the documentation:

``` javascript
myReadableStreamBuffer.put('A String', 'utf8');
```

What I tried, causing my program not to work:

``` javascript
myReadableStreamBuffer.put('1f8bde5a7435', 'hex');
```

How I fixed it:

``` javascript
var myBuffer = new Buffer('1f8bde5a7435', 'hex');
cipherData.put(myBuffer);
```

It would be nice, if that could be fixed. Even though not explicitly documented, the readme implies that 'hex' should work.

**Comment by samcday** [comment]
Someone must have fixed it in the intervening year and a half since this ticket was raised ;)

I wrote a test in commit 78d2e1a just now, `put()`ing hex encoded into a `ReadableStreamBuffer` works fine.
