### ISSUE TITLE
ReadableStreamBuffer causing memory usage to grow 100% and eventually cause unresponsive system

### ISSUE THREAD

**Issue by SameerTi** [samcday/node-stream-buffer#31]
I am using ReadableStreamBuffer to do Download Speed Test via FTP protocol

So for example Test pattern is such that:
100 parallel threads/users initiating FTP download of 100 MBs 

`var o_DownloadBufferSize=1024 * 1024; // 1MB Buffer
var o_DownloadBuffer=new Buffer(o_DownloadBufferSize);
o_DownloadBuffer.fill("0xFF"); 

for (var nBytesSentMB=1; nBytesSentMB<=100 ; nBytesSentMB+= 1) {
	myReadableStreamBuffer.put(o_DownloadBuffer);
}
`

This makes the whole system unresponsive and memory usage grows beyond 98% and does not free up for long long time

**Comment by SameerTi** [comment]
Any suggestion? update ?

**Comment by samcday** [comment]
I'm not quite sure what you were trying to achieve, but if you create a `ReadableStreamBuffer` that doesn't have anything reading from it, then it will continue to accumulate data in-memory until your system runs out of memory ;)
