### ISSUE TITLE
The package is unlicensed

### ISSUE THREAD

**Issue by omrisdeor11** [samcday/node-stream-buffer#57]
I would like to use a package whose dependencies contains this package as well, and it is not licensed, which makes it difficult for me to use... Is there any workaround this?
Thx :)

**Comment by samcday** [comment]
Do you have a specific issue with the [Unlicense](https://en.wikipedia.org/wiki/Unlicense)? It explicitly releases this code into the public domain.

**Comment by samcday** [comment]
I saw that you also raised this concern on the kubernetes-client/javascript package, which is using stream-buffers as a dependency. The maintainer indicated that Unlicense is compatible with Apache 2.0.

I'm going to close this issue now, please feel free to comment if you have any further concerns/questions, though.
